### ISSUE TITLE
Potential Typo

### ISSUE THREAD

**Issue by Bulletninja** [happykit/auth-email#5]
https://github.com/happykit/auth-email/blob/9dc57ceb5c194e4965b56fbdffa3981744ed67b8/auth-email/src-app/api/index.ts#L248

I think this should be serverConfig.cookieName

**Comment by dferber90** [comment]
Good catch, that's definitely wrong

**Comment by dferber90** [comment]
This has since been fixed, thanks for reporting! https://github.com/happykit/auth-email/blob/9dc57ceb5c194e4965b56fbdffa3981744ed67b8/auth-email/src-app/api/index.ts#L87
